"""
tools/zone_selector.py
-----------------------
Interactive helper to define platform zones on YOUR OWN camera footage
instead of the default equal-thirds split in config/zones.json.

Requires a local display (this will not run inside a headless server/
sandbox) -- run it on your own machine.

Usage:
    python tools/zone_selector.py --video path/to/your_footage.mp4 --output config/zones.json

Controls:
    Left click   add a point to the current zone polygon
    n            finish current zone (prompts for name + capacity in the
                 terminal), start a new one
    u            undo the last point
    s            save all completed zones to the output JSON and exit
    q            quit without saving
"""

import argparse
import json
import os

import cv2

current_points = []
all_zones = []
frame_for_draw = None
frame_w, frame_h = None, None


def mouse_callback(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        current_points.append((x, y))


def redraw(base_frame):
    img = base_frame.copy()
    colors = [(0, 255, 0), (0, 200, 255), (255, 100, 0), (255, 0, 200), (0, 0, 255)]
    for i, zone in enumerate(all_zones):
        pts = zone["polygon_px"]
        color = colors[i % len(colors)]
        for j in range(len(pts)):
            cv2.line(img, pts[j], pts[(j + 1) % len(pts)], color, 2)
        cx = int(sum(p[0] for p in pts) / len(pts))
        cy = int(sum(p[1] for p in pts) / len(pts))
        cv2.putText(img, zone["name"], (cx - 30, cy), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    for i, p in enumerate(current_points):
        cv2.circle(img, p, 4, (255, 255, 255), -1)
        if i > 0:
            cv2.line(img, current_points[i - 1], p, (255, 255, 255), 1)
    if len(current_points) > 2:
        cv2.line(img, current_points[-1], current_points[0], (180, 180, 180), 1)

    cv2.putText(
        img, "L-click: add point | n: finish zone | u: undo | s: save+exit | q: quit",
        (10, img.shape[0] - 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1,
    )
    return img


def main():
    global frame_w, frame_h

    parser = argparse.ArgumentParser()
    parser.add_argument("--video", required=True, help="Path to a representative video/frame source")
    parser.add_argument("--output", default="config/zones.json")
    args = parser.parse_args()

    cap = cv2.VideoCapture(args.video)
    ok, frame = cap.read()
    cap.release()
    if not ok:
        raise SystemExit(f"Could not read a frame from {args.video}")

    frame_h, frame_w = frame.shape[:2]

    cv2.namedWindow("Zone Selector")
    cv2.setMouseCallback("Zone Selector", mouse_callback)

    while True:
        cv2.imshow("Zone Selector", redraw(frame))
        key = cv2.waitKey(20) & 0xFF

        if key == ord("u") and current_points:
            current_points.pop()

        elif key == ord("n"):
            if len(current_points) < 3:
                print("Need at least 3 points to close a zone polygon -- keep clicking.")
                continue
            name = input("Zone name (e.g. 'Zone A - Near Stairs'): ").strip() or f"Zone {len(all_zones) + 1}"
            cap_str = input("Comfortable capacity for this zone (integer): ").strip()
            capacity = int(cap_str) if cap_str.isdigit() else 10
            all_zones.append(
                {
                    "id": f"zone_{chr(97 + len(all_zones))}",
                    "name": name,
                    "polygon_px": list(current_points),
                    "capacity": capacity,
                }
            )
            current_points.clear()
            print(f"Saved '{name}'. Click points for the next zone, or press 's' to finish.")

        elif key == ord("s"):
            if current_points and len(current_points) >= 3:
                print("You have an unfinished zone -- press 'n' first to finish it, or 'u' to discard points.")
                continue
            zones_json = {
                "_comment": "Generated by tools/zone_selector.py. Polygon points are normalized (0-1).",
                "zones": [
                    {
                        "id": z["id"],
                        "name": z["name"],
                        "polygon": [[px / frame_w, py / frame_h] for px, py in z["polygon_px"]],
                        "capacity": z["capacity"],
                    }
                    for z in all_zones
                ],
                "density_thresholds": {"low": 0.4, "medium": 0.7, "high": 0.9},
            }
            os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
            with open(args.output, "w") as f:
                json.dump(zones_json, f, indent=2)
            print(f"Saved {len(all_zones)} zones to {args.output}")
            break

        elif key == ord("q"):
            print("Quit without saving.")
            break

    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
